Fix for error AttributeError: 'NoneType' object has no attribute 'target'
- Now checks JobRecord and its target value
- Updated to Squonk2 client API 1.3.0